services:
#  web:
#    build: .
#    image: ipay2_web:latest
#    container_name: ipay2_app
#    command: >
#      bash -c "
#        python manage.py migrate &&
#        python manage.py collectstatic --noinput &&
#        gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=3"
#    volumes:
#      - static_volume:/app/staticfiles
#      # - media_volume:/app/mediafiles # Если используете
#    expose:
#      - "8000"
#    env_file:
#      - .env
#    depends_on:
#      - db
  redis:
    image: redis:7-alpine
    container_name: verben_redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy volatile-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

#appendonly yes	включает persistence
#maxmemory 256mb	лимит памяти
#volatile-lru	удаляет ключи с TTL

  db:
    image: postgres:18.1
    container_name: verben_db
    restart: always
    env_file:
      - .env
    volumes:
      - verben_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  verben_postgres_data:
  redis_data: