services:
  web:
    build: .
    image: verben_web:latest
    container_name: verben_app
    volumes:
      - static_data:/app/staticfiles
      # - media_volume:/app/mediafiles # Если используете
      - ./logs:/app/logs    # Bind Mount для логов
    expose:
      - "8000"
    env_file:
      - .env_prod
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    container_name: verben_redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy volatile-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

#appendonly yes	включает persistence
#maxmemory 256mb	лимит памяти
#volatile-lru	удаляет ключи с TTL

  db:
    image: postgres:18.1
    container_name: verben_db
    restart: always
    env_file:
      - .env_prod
    volumes:
      - verben_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.26.1-alpine
    container_name: verben_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro # Файл с паролем
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs/nginx:/var/log/nginx             # Папка для логов Nginx
      - ./logs/report:/app/report:ro            # Папка, где лежит отчет для просмотра
    depends_on:
      - web
      - goaccess

  goaccess:
    image: allinurl/goaccess:1.10.1
    container_name: verben_goaccess
    ports:
      - "7890:7890"
    restart: always
    volumes:
      - ./logs/nginx:/opt/goaccess/logs:ro      # Читает логи отсюда
      - ./logs/report:/opt/goaccess/out         # Пишет отчет сюда
    command: >
      /opt/goaccess/logs/access.log
      --log-format=COMBINED
      --output=/opt/goaccess/out/stats.html
      --real-time-html
      --ws-url=wss://deutsch-core.de/ws
      --persist

volumes:
  verben_postgres_data:
  redis_data:
  static_data: