# Generated by Django 6.0.1 on 2026-02-27 02:03

import src.common.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='Niveau')),
                ('skill_type', models.CharField(choices=[('translation', 'Übersetzung'), ('praesens', 'Präsens'), ('praeteritum', 'Präteritum'), ('perfekt', 'Perfekt')], default='translation', max_length=20, verbose_name='Fähigkeit')),
                ('title', models.CharField(max_length=200, verbose_name='Überschrift')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Lerneinheit',
                'verbose_name_plural': 'Lerneinheiten',
            },
        ),
        migrations.CreateModel(
            name='Preposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, unique=True)),
                ('case_requirement', models.CharField(choices=[('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv'), ('MIXED', 'gemischt')], max_length=5)),
            ],
            options={
                'verbose_name': 'Präposition',
                'verbose_name_plural': 'Präpositionen',
            },
        ),
        migrations.CreateModel(
            name='UserVerbProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('translation', 'Übersetzung'), ('praesens', 'Präsens'), ('praeteritum', 'Präteritum'), ('perfekt', 'Perfekt')], max_length=20, verbose_name='Fähigkeit')),
                ('pronoun', models.CharField(blank=True, help_text='Leer bei Übersetzungsaufgaben', max_length=20, null=True, verbose_name='Pronomen')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Richtige Antworten')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='Falsche Antworten')),
                ('streak', models.PositiveIntegerField(default=0, help_text='Anzahl der richtigen Antworten in Folge', verbose_name='Aktuelle Serie')),
                ('mastered', models.BooleanField(default=False, help_text='Wird als gelernt betrachtet', verbose_name='Beherrscht')),
                ('last_answer_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Antwort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Verbfortschritt',
                'verbose_name_plural': 'Verbfortschritte',
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=50, unique=True, verbose_name='Infinitivform')),
                ('verb_type', models.CharField(choices=[('reg', 'schwach'), ('str', 'stark'), ('mix', 'gemischt')], default=src.common.choices.VerbType['REGULAR'], max_length=10, verbose_name='Konjugation')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default=src.common.choices.CEFRLevel['A1'], max_length=2, verbose_name='Niveau')),
                ('reflexivitaet', models.CharField(choices=[('nrefl', 'nicht reflexiv'), ('refl', 'unechte reflexiv'), ('erefl', 'echte reflexiv')], default=src.common.choices.Reflexiv['NREFL'], max_length=16, verbose_name='Reflexivität')),
                ('is_trennbare', models.BooleanField(default=False, verbose_name='Trennbarkeit')),
                ('case', models.CharField(blank=True, choices=[('AKK', 'Akkusativ'), ('DAT', 'Dativ')], max_length=3, null=True, verbose_name='Kasusrektion')),
                ('auxiliary', models.CharField(blank=True, choices=[('haben', 'haben'), ('sein', 'sein')], max_length=10, null=True, verbose_name='Hilfsverb')),
                ('participle_ii', models.CharField(blank=True, max_length=50, null=True, verbose_name='Partizip 2')),
            ],
            options={
                'verbose_name': 'Verb',
                'verbose_name_plural': 'Verben',
            },
        ),
        migrations.CreateModel(
            name='VerbForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(choices=[('Präsens', 'Präsens'), ('Präteritum', 'Präteritum'), ('Perfekt', 'Perfekt')], max_length=15, verbose_name='Zeitform')),
                ('pronoun', models.CharField(choices=[('ich', 'ich'), ('du', 'du'), ('er/sie/es', 'er/sie/es'), ('wir', 'wir'), ('ihr', 'ihr'), ('sie', 'sie')], max_length=20, verbose_name='Pronomen')),
                ('form', models.CharField(max_length=50, verbose_name='Personalform')),
            ],
            options={
                'verbose_name': 'Personalform',
                'verbose_name_plural': 'Personalformen',
            },
        ),
        migrations.CreateModel(
            name='VerbPreposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(blank=True, choices=[('NOM', 'Nominativ'), ('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv')], max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Verb mit Präposition',
                'verbose_name_plural': 'Verben mit Präposition',
            },
        ),
        migrations.CreateModel(
            name='VerbTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'Englisch'), ('ru', 'Russisch'), ('uk', 'Ukrainisch')], max_length=2, verbose_name='Sprache')),
                ('translation', models.CharField(max_length=100, verbose_name='Übersetzung')),
            ],
            options={
                'verbose_name': 'Übersetzung',
                'verbose_name_plural': 'Übersetzungen',
            },
        ),
    ]
