# Generated by Django 6.0.1 on 2026-02-12 10:58

import django.db.models.deletion
import src.common.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=50, unique=True)),
                ('verb_type', models.CharField(choices=[('regular', 'regular'), ('strong', 'strong'), ('mixed', 'mixed')], default=src.common.choices.VerbType['REGULAR'], max_length=10)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default=src.common.choices.CEFRLevel['A1'], max_length=2)),
                ('auxiliary', models.CharField(blank=True, choices=[('haben', 'haben'), ('sein', 'sein')], max_length=10, null=True)),
                ('participle_ii', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('tense', models.CharField(choices=[('Präsens', 'Präsens'), ('Präteritum', 'Präteritum'), ('Perfekt', 'Perfekt')], max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('verbs', models.ManyToManyField(blank=True, related_name='learning_units', to='personal_forms.verb')),
            ],
        ),
        migrations.CreateModel(
            name='VerbForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(choices=[('Präsens', 'Präsens'), ('Präteritum', 'Präteritum'), ('Perfekt', 'Perfekt')], max_length=15)),
                ('pronoun', models.CharField(choices=[('ich', 'ich'), ('du', 'du'), ('er/sie/es', 'er/sie/es'), ('wir', 'wir'), ('ihr', 'ihr'), ('sie', 'sie')], max_length=20)),
                ('form', models.CharField(max_length=50)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='personal_forms.verb')),
            ],
            options={
                'unique_together': {('verb', 'tense', 'pronoun')},
            },
        ),
    ]
