# Generated by Django 6.0.1 on 2026-02-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraesensVerbForm',
            fields=[
            ],
            options={
                'verbose_name': 'Form (Präsens)',
                'verbose_name_plural': 'Konjugation: Präsens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personal_forms.verbform',),
        ),
        migrations.CreateModel(
            name='PraeteritumVerbForm',
            fields=[
            ],
            options={
                'verbose_name': 'Form (Präteritum)',
                'verbose_name_plural': 'Konjugation: Präteritum',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personal_forms.verbform',),
        ),
        migrations.CreateModel(
            name='VerbTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('translation', models.CharField(max_length=100)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='personal_forms.verb')),
            ],
            options={
                'unique_together': {('verb', 'language_code')},
            },
        ),
    ]
