# Generated by Django 6.0.1 on 2026-02-27 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userverbprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_progress', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='userverbprogress',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='personal_forms.verb', verbose_name='Verb'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='verbs',
            field=models.ManyToManyField(blank=True, related_name='learning_units', to='personal_forms.verb'),
        ),
        migrations.AddField(
            model_name='verbform',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='personal_forms.verb'),
        ),
        migrations.AddField(
            model_name='verbpreposition',
            name='preposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='personal_forms.preposition'),
        ),
        migrations.AddField(
            model_name='verbpreposition',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepositions', to='personal_forms.verb'),
        ),
        migrations.AddField(
            model_name='verbtranslation',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='personal_forms.verb'),
        ),
        migrations.AddIndex(
            model_name='userverbprogress',
            index=models.Index(fields=['user', 'skill_type'], name='personal_fo_user_id_f54bae_idx'),
        ),
        migrations.AddIndex(
            model_name='userverbprogress',
            index=models.Index(fields=['user', 'mastered'], name='personal_fo_user_id_f85a67_idx'),
        ),
        migrations.AddIndex(
            model_name='userverbprogress',
            index=models.Index(fields=['user', 'verb', 'skill_type', 'pronoun'], name='personal_fo_user_id_6c78b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userverbprogress',
            unique_together={('user', 'verb', 'skill_type', 'pronoun')},
        ),
        migrations.AlterUniqueTogether(
            name='verbform',
            unique_together={('verb', 'tense', 'pronoun')},
        ),
        migrations.AlterUniqueTogether(
            name='verbpreposition',
            unique_together={('verb', 'preposition', 'case')},
        ),
        migrations.AlterUniqueTogether(
            name='verbtranslation',
            unique_together={('verb', 'language_code')},
        ),
    ]
