# Generated by Django 6.0.1 on 2026-03-04 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='assigned_courses', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesene Schüler'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_units', to='personal_forms.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='userverbprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_progress', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AddField(
            model_name='userverbprogress',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='personal_forms.verb', verbose_name='Verb'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='verbs',
            field=models.ManyToManyField(blank=True, related_name='learning_units', to='personal_forms.verb'),
        ),
        migrations.AddField(
            model_name='verbform',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='personal_forms.verb'),
        ),
        migrations.AddField(
            model_name='verbpreposition',
            name='preposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='personal_forms.preposition'),
        ),
        migrations.AddField(
            model_name='verbpreposition',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepositions', to='personal_forms.verb'),
        ),
        migrations.AddField(
            model_name='verbtranslation',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='personal_forms.verb'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['author', 'visibility'], name='personal_fo_author__0129e4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['visibility'], name='personal_fo_visibil_6cbeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='userverbprogress',
            index=models.Index(fields=['user', 'skill_type'], name='personal_fo_user_id_f54bae_idx'),
        ),
        migrations.AddIndex(
            model_name='userverbprogress',
            index=models.Index(fields=['user', 'mastered'], name='personal_fo_user_id_f85a67_idx'),
        ),
        migrations.AddIndex(
            model_name='userverbprogress',
            index=models.Index(fields=['user', 'verb', 'skill_type', 'pronoun'], name='personal_fo_user_id_6c78b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userverbprogress',
            unique_together={('user', 'verb', 'skill_type', 'pronoun')},
        ),
        migrations.AddIndex(
            model_name='learningunit',
            index=models.Index(fields=['course', 'order'], name='personal_fo_course__b41348_idx'),
        ),
        migrations.AddIndex(
            model_name='learningunit',
            index=models.Index(fields=['course', 'level'], name='personal_fo_course__26efba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verbform',
            unique_together={('verb', 'tense', 'pronoun')},
        ),
        migrations.AlterUniqueTogether(
            name='verbpreposition',
            unique_together={('verb', 'preposition', 'case')},
        ),
        migrations.AlterUniqueTogether(
            name='verbtranslation',
            unique_together={('verb', 'language_code')},
        ),
    ]
