# Generated by Django 6.0.1 on 2026-02-14 14:31

import django.db.models.deletion
import src.common.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0002_praesensverbform_praeteritumverbform_verbtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, unique=True)),
                ('case_requirement', models.CharField(choices=[('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv'), ('MIXED', 'gemischt')], max_length=5)),
            ],
            options={
                'verbose_name': 'Präposition',
                'verbose_name_plural': 'Präpositionen',
            },
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'verbose_name': 'Lerneinheit', 'verbose_name_plural': 'Lerneinheiten'},
        ),
        migrations.AlterModelOptions(
            name='verb',
            options={'verbose_name': 'Verb', 'verbose_name_plural': 'Verben'},
        ),
        migrations.AlterModelOptions(
            name='verbform',
            options={'verbose_name': 'Personalform', 'verbose_name_plural': 'Personalformen'},
        ),
        migrations.AlterModelOptions(
            name='verbtranslation',
            options={'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AddField(
            model_name='verb',
            name='case',
            field=models.CharField(blank=True, choices=[('NOM', 'Nominativ'), ('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='is_reflexive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verb',
            name='is_trennbare',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verb',
            name='verb_type',
            field=models.CharField(choices=[('schwach', 'schwach'), ('stark', 'stark'), ('gemischt', 'gemischt')], default=src.common.choices.VerbType['REGULAR'], max_length=10),
        ),
        migrations.CreateModel(
            name='VerbPreposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(blank=True, choices=[('NOM', 'Nominativ'), ('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv')], max_length=3, null=True)),
                ('preposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='personal_forms.preposition')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepositions', to='personal_forms.verb')),
            ],
            options={
                'verbose_name': 'Verb mit Präposition',
                'verbose_name_plural': 'Verben mit Präposition',
                'unique_together': {('verb', 'preposition', 'case')},
            },
        ),
    ]
