# Generated by Django 6.0.1 on 2026-03-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='{}', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='preposition',
            name='case_requirement',
            field=models.CharField(choices=[('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv'), ('MIXED', 'gemischt')], max_length=5, verbose_name='Kasusforderung'),
        ),
        migrations.AlterField(
            model_name='preposition',
            name='text',
            field=models.CharField(max_length=20, unique=True, verbose_name='Präposition'),
        ),
        migrations.AlterField(
            model_name='verbform',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='personal_forms.verb', verbose_name='Verb'),
        ),
        migrations.AlterField(
            model_name='verbpreposition',
            name='case',
            field=models.CharField(blank=True, choices=[('NOM', 'Nominativ'), ('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv')], max_length=3, null=True, verbose_name='Kasus'),
        ),
        migrations.AlterField(
            model_name='verbpreposition',
            name='preposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbs', to='personal_forms.preposition', verbose_name='Präposition'),
        ),
        migrations.AlterField(
            model_name='verbpreposition',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepositions', to='personal_forms.verb', verbose_name='Verb'),
        ),
        migrations.AlterField(
            model_name='verbtranslation',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='personal_forms.verb', verbose_name='Verb'),
        ),
    ]
