# Generated by Django 6.0.1 on 2026-03-19 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0003_alter_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название набора слов')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_groups', to='personal_forms.course', verbose_name='Kurse')),
                ('verbs', models.ManyToManyField(related_name='verb_groups', to='personal_forms.verb', verbose_name='Verben')),
            ],
        ),
        migrations.AddField(
            model_name='learningunit',
            name='verb_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='personal_forms.verbgroup', verbose_name='Verbgruppe'),
        ),
    ]
