# Generated by Django 6.0.1 on 2026-02-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0003_preposition_alter_learningunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='case',
            field=models.CharField(blank=True, choices=[('NOM', 'Nominativ'), ('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv')], max_length=9, null=True),
        ),
    ]
