# Generated by Django 6.0.1 on 2026-02-14 17:40

import src.common.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0004_alter_verb_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='is_reflexive',
        ),
        migrations.AddField(
            model_name='verb',
            name='reflexivitaet',
            field=models.CharField(choices=[('nicht reflexiv', 'nicht reflexiv'), ('unechte reflexiv', 'unechte reflexiv'), ('echte reflexiv', 'echte reflexiv')], default=src.common.choices.Reflexiv['NREFL'], max_length=16, verbose_name='Reflexivität'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='auxiliary',
            field=models.CharField(blank=True, choices=[('haben', 'haben'), ('sein', 'sein')], max_length=10, null=True, verbose_name='Hilfsverb'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='case',
            field=models.CharField(blank=True, choices=[('NOM', 'Nominativ'), ('AKK', 'Akkusativ'), ('DAT', 'Dativ'), ('GEN', 'Genitiv')], max_length=9, null=True, verbose_name='Kasusrektion'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='infinitive',
            field=models.CharField(max_length=50, unique=True, verbose_name='Infinitivform'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='is_trennbare',
            field=models.BooleanField(default=False, verbose_name='Trennbarkeit'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default=src.common.choices.CEFRLevel['A1'], max_length=2, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='participle_ii',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partizip 2'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='verb_type',
            field=models.CharField(choices=[('schwach', 'schwach'), ('stark', 'stark'), ('gemischt', 'gemischt')], default=src.common.choices.VerbType['REGULAR'], max_length=10, verbose_name='Konjugation'),
        ),
    ]
