# Generated by Django 6.0.1 on 2026-03-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0005_auto_20260319_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='verbs',
        ),
    ]
