# Generated by Django 6.0.1 on 2026-02-15 11:12

import src.common.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0005_remove_verb_is_reflexive_verb_reflexivitaet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PraesensVerbForm',
        ),
        migrations.DeleteModel(
            name='PraeteritumVerbForm',
        ),
        migrations.AlterModelOptions(
            name='verbtranslation',
            options={'verbose_name': 'Übersetzung', 'verbose_name_plural': 'Übersetzungen'},
        ),
        migrations.AlterField(
            model_name='verb',
            name='reflexivitaet',
            field=models.CharField(choices=[('nrefl', 'nicht reflexiv'), ('refl', 'unechte reflexiv'), ('erefl', 'echte reflexiv')], default=src.common.choices.Reflexiv['NREFL'], max_length=16, verbose_name='Reflexivität'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='verb_type',
            field=models.CharField(choices=[('reg', 'schwach'), ('str', 'stark'), ('mix', 'gemischt')], default=src.common.choices.VerbType['REGULAR'], max_length=10, verbose_name='Konjugation'),
        ),
        migrations.AlterField(
            model_name='verbform',
            name='form',
            field=models.CharField(max_length=50, verbose_name='Personalform'),
        ),
        migrations.AlterField(
            model_name='verbform',
            name='pronoun',
            field=models.CharField(choices=[('ich', 'ich'), ('du', 'du'), ('er/sie/es', 'er/sie/es'), ('wir', 'wir'), ('ihr', 'ihr'), ('sie', 'sie')], max_length=20, verbose_name='Pronomen'),
        ),
        migrations.AlterField(
            model_name='verbform',
            name='tense',
            field=models.CharField(choices=[('Präsens', 'Präsens'), ('Präteritum', 'Präteritum'), ('Perfekt', 'Perfekt')], max_length=15, verbose_name='Zeitform'),
        ),
        migrations.AlterField(
            model_name='verbtranslation',
            name='language_code',
            field=models.CharField(max_length=10, verbose_name='Sprache'),
        ),
        migrations.AlterField(
            model_name='verbtranslation',
            name='translation',
            field=models.CharField(max_length=100, verbose_name='Übersetzung'),
        ),
    ]
