# Generated by Django 6.0.1 on 2026-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0006_delete_praesensverbform_delete_praeteritumverbform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbtranslation',
            name='language_code',
            field=models.CharField(choices=[('en', 'Englisch'), ('ru', 'Russisch'), ('uk', 'Ukrainisch')], max_length=2, verbose_name='Sprache'),
        ),
    ]
