# Generated by Django 6.0.1 on 2026-03-19 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0006_remove_learningunit_verbs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verbgroup',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verb_groups', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='verb_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='personal_forms.verbgroup', verbose_name='Wortschatz'),
        ),
        migrations.AlterField(
            model_name='verbgroup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel des Wortschatzes'),
        ),
    ]
