# Generated by Django 6.0.1 on 2026-02-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0007_alter_verbtranslation_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='case',
            field=models.CharField(blank=True, choices=[('AKK', 'Akkusativ'), ('DAT', 'Dativ')], max_length=3, null=True, verbose_name='Kasusrektion'),
        ),
    ]
