# Generated by Django 6.0.1 on 2026-02-20 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0008_alter_verb_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='tense',
            field=models.CharField(choices=[('Präsens', 'Präsens'), ('Präteritum', 'Präteritum'), ('Perfekt', 'Perfekt')], max_length=15, verbose_name='Zeitform'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Überschrift'),
        ),
        migrations.CreateModel(
            name='UserVerbProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('translation', 'Translation'), ('praesens', 'Präsens'), ('praeteritum', 'Präteritum'), ('perfekt', 'Perfekt')], max_length=20, verbose_name='Fähigkeit')),
                ('pronoun', models.CharField(blank=True, help_text='Leer bei Übersetzungsaufgaben', max_length=20, null=True, verbose_name='Pronomen')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Richtige Antworten')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='Falsche Antworten')),
                ('streak', models.PositiveIntegerField(default=0, help_text='Anzahl der richtigen Antworten in Folge', verbose_name='Aktuelle Serie')),
                ('mastered', models.BooleanField(default=False, help_text='Wird als gelernt betrachtet', verbose_name='Beherrscht')),
                ('last_answer_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Antwort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_progress', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='personal_forms.verb', verbose_name='Verb')),
            ],
            options={
                'verbose_name': 'Verbfortschritt',
                'verbose_name_plural': 'Verbfortschritte',
                'indexes': [models.Index(fields=['user', 'skill_type'], name='personal_fo_user_id_f54bae_idx'), models.Index(fields=['user', 'mastered'], name='personal_fo_user_id_f85a67_idx')],
                'unique_together': {('user', 'verb', 'skill_type', 'pronoun')},
            },
        ),
    ]
