# Generated by Django 6.0.1 on 2026-03-19 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0008_auto_20260319_1503'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbgroup',
            name='course',
        ),
        migrations.AlterField(
            model_name='verbgroup',
            name='author',
            field=models.ForeignKey(default='fdd5cf8e-3605-4a30-bbd5-c8f68738f9be', on_delete=django.db.models.deletion.CASCADE, related_name='verb_groups', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
