# Generated by Django 6.0.1 on 2026-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0009_remove_verbgroup_course_alter_verbgroup_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbform',
            name='pronoun',
            field=models.CharField(choices=[('ich', 'ich'), ('du', 'du'), ('er/sie/es', 'er/sie/es'), ('wir', 'wir'), ('ihr', 'ihr'), ('sie', 'sie/Sie')], max_length=20, verbose_name='Pronomen'),
        ),
    ]
