# Generated by Django 6.0.1 on 2026-02-25 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_forms', '0009_alter_learningunit_level_alter_learningunit_tense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='tense',
        ),
        migrations.AddField(
            model_name='learningunit',
            name='skill_type',
            field=models.CharField(choices=[('translation', 'Übersetzung'), ('praesens', 'Präsens'), ('praeteritum', 'Präteritum'), ('perfekt', 'Perfekt')], default='translation', max_length=20, verbose_name='Fähigkeit'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Überschrift'),
        ),
        migrations.AlterField(
            model_name='userverbprogress',
            name='skill_type',
            field=models.CharField(choices=[('translation', 'Übersetzung'), ('praesens', 'Präsens'), ('praeteritum', 'Präteritum'), ('perfekt', 'Perfekt')], max_length=20, verbose_name='Fähigkeit'),
        ),
        migrations.AddIndex(
            model_name='userverbprogress',
            index=models.Index(fields=['user', 'verb', 'skill_type', 'pronoun'], name='personal_fo_user_id_6c78b2_idx'),
        ),
    ]
