# Generated by Django 6.0.1 on 2026-03-05 12:20

import src.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvitation',
            name='expires_at',
            field=models.DateTimeField(default=src.users.models.default_expiry, help_text='Nach diesem Datum verliert der Code seine Gültigkeit', verbose_name='Ablaufdatum'),
        ),
    ]
