# Generated by Django 6.0.1 on 2026-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profilbild des Benutzers.', null=True, upload_to='avatars/', verbose_name='Profilbild'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Geburtsdatum des Benutzers.', null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Schüler'), ('teacher', 'Lehrer'), ('admin', 'Administrator')], default='student', help_text='Bestimmt die Benutzerrolle im System.', max_length=20, verbose_name='Rolle'),
        ),
    ]
