################################
# LOG INPUT
################################

log-file /opt/goaccess/logs/access.log

################################
# LOG FORMAT
################################

log-format COMBINED
#date-format %d/%b/%Y
#time-format %H:%M:%S

################################
# OUTPUT
################################

output /opt/goaccess/out/stats.html

################################
# REALTIME HTML
################################

real-time-html true
#addr 0.0.0.0
#port 7890

ws-url wss://deutsch-core.de:443/ws

################################
# DATABASE (чтобы статистика сохранялась)
################################

persist true
restore true
db-path /opt/goaccess/db
keep-last 30

################################
# UI
################################

max-items 50
html-prefs {"theme":"dark"}

################################
# FILTERS
################################

ignore-crawlers true

################################
# GEOLOCATION
################################

#geoip-database /opt/goaccess/geoip/GeoLite2-City.mmdb